# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_study"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_study"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_study:
    +post-hook:
      - |
        CREATE SCHEMA IF NOT EXISTS logs;
        CREATE TABLE IF NOT EXISTS {{ target.database }}.logs.dbt_logs (
            event_date timestamp,
            event_name varchar(100),
            node_name varchar(256)
        );
        INSERT INTO {{ target.database }}.logs.dbt_logs
        (event_date, event_name, node_name)
        VALUES (
            CURRENT_TIMESTAMP, 'finish run model', '{{ this.name }}'
        );
      - "{{ check_dependencies(this.name) }}"
    +meta:
      owner: "kovalchukpv61@gmail.com"
      year_created: 2025
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: table
      +tags: ["staging"]
      +schema: staging # ← Создаст схему staging
    intermediate:
      +materialized: table
      +tags: ["intermediate"]
      +schema: intermediate # ← Создаст схему intermediate
    marts:
      +materialized: table
      +tags: ["marts"]
      +schema: marts # ← Создаст схему marts

seeds:
  dbt_study:
    +schema: seeds # ← Схема для seeds
